env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - "plugin:react/recommended"
  - "plugin:jest/recommended"
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - jest
  - react
  - "@typescript-eslint"
rules:
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": [error, { "varsIgnorePattern": "^_" }]
  react/react-in-jsx-scope: 0
  max-len: [1, 80]
