env:
  browser: true
  es6: true
  node: true
extends:
  - "plugin:react/recommended"
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": error
  react/react-in-jsx-scope: 0
