env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  - "plugin:react/recommended"
  - "plugin:jest/recommended"
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - jest
rules: {}
