openapi: "3.0.2"
info:
  title: HCW flu study app API
  version: "1.0"
servers:
  - url: https://reports.hcwflustudy.com/api
paths:
  /users:
    get:
      summary: List all users
      security:
        - Admin: []
      responses:
        "200":
          description: Array of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      summary: Add users
      security:
        - Admin: []
      requestBody:
        description: Users to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Users"
      responses:
        "204":
          description: Successful addition
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    delete:
      summary: Delete a user
      security:
        - Admin: []
      parameters:
        - in: query
          name: email
          schema:
            type: string
      responses:
        "204":
          description: Successful deletion
        "401":
          $ref: "#/components/responses/UnauthorizedError"

components:
  schemas:
    User:
      type: object
      required:
        - email
        - accessGroup
      properties:
        email:
          type: string
        accessGroup:
          enum:
            [
              admin,
              unrestricted,
              melbourne,
              sydney,
              adelaide,
              brisbane,
              newcastle,
              perth,
            ]
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
  securitySchemes:
    User:
      type: http
      scheme: bearer
    Admin:
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
