openapi: "3.0.2"
info:
  title: HCW flu study app API
  version: "1.0"
servers:
  - url: https://reports.hcwflustudy.com/api
paths:
  /users:
    get:
      summary: List all users
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Array of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
    post:
      summary: Add users
      requestBody:
        description: Users to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Users"
      responses:
        "204":
          description: Successful addition

components:
  schemas:
    User:
      type: object
      required:
        - email
        - accessGroup
      properties:
        email:
          type: string
        accessGroup:
          enum: [admin, unrestricted]
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
