db:
  accessGroups:
    - adelaide
    - brisbane
    - melbourne
    - newcastle
    - perth
    - sydney
    - unrestricted
    - admin
  users:
    - email: khvorov45@gmail.com
      accessGroup: admin
  postgres:
    user: postgres
    host: localhost
    database: hcwstudyapp-dev
    password:
    port: 3001
    tableResetSqlPath: db/table-reset-postgres.sql
  redcap:
    url: https://biredcap.mh.org.au/api/
    token:
email:
  user: sen.khvorov@unimelb.edu.au
  password:
  host: smtp.office365.com
  port: 587
