Participant:
  - my: redcapRecordId
    redcap: record_id
    label: Record ID
  - my: pid
    redcap: pid
    label: PID
  - my: accessGroup
    redcap: redcap_data_access_group
    label: Access Group
  - my: site
    redcap: site_name
    label: Site
  - my: dob
    redcap: a2_dob
    label: Date of Birth
  - my: dateScreening
    redcap: date_screening
    label: Date of Screening
  - my: email
    redcap: email
    label: Email
  - my: mobile
    redcap: mobile_number
    label: Mobile
  - my: age
    redcap:
    label: Age
  - my: gender
    redcap: a1_gender
    label: Gender
  - my: numSeasVac
    redcap: num_seas_vac
    label: Previous Vaccinations
  - my: day
    redcap:
    label: Day
  - my: date
    redcap:
    label: Date
  - my: day0
    redcap: scheduled_date_v0
    label: Day 0
  - my: day7
    redcap: scheduled_date_v7
    label: Day 7
  - my: day14
    redcap: scheduled_date_v14
    label: Day 14
  - my: day280
    redcap: scheduled_date_v280
    label: Day 280
